spring.application.name=gateway-service
server.port=9000

# Configuración de rutas
# Si alguien pide /products/** lo mandamos al microservicio de productos
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**

# Si alguien pide /inventory/** lo mandamos al de inventario
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=lb://inventory-service
spring.cloud.gateway.routes[1].predicates[1]=Path=/inventory/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/