spring.application.name=gateway-service
server.port=9000

# Conexión a Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuración de Rutas dinámicas (esto crea rutas automáticas como /product-service/...)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# --- RUTA 0: PRODUCTOS ---
spring.cloud.gateway.routes[0].id=product-route
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v01/products/**
# StripPrefix=3 si quieres que al microservicio le llegue solo lo que va después de /products/
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

# --- RUTA 1: INVENTARIO (Cambiamos el índice a [1]) ---
spring.cloud.gateway.routes[1].id=inventory-route
spring.cloud.gateway.routes[1].uri=lb://inventory-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v01/inventory/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=3