spring.application.name=product-service


server.port=9090

# Configuración de Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/product_inventory_db
spring.datasource.username=postgres
spring.datasource.password=admin123

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

