spring.application.name=inventory-service
server.port=9091

# Conexión a su propia base de datos (diferente a la de productos)
spring.datasource.url=jdbc:postgresql://localhost:5432/product_inventory_db
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/